docs/usage.rst, tests/test_namelist.py
Closes #24 
Adds documentation for `enable_restart` which was introduced in #9 without docs. Also improves organization of unit tests for `enable_restart` by adding them to a new TestClass and changing order of functions for clarity.
=> Add enable_restart docs and move tests to new class

docs/usage.rst, fv3config/__init__.py, fv3config/refresh_data.py
=> Moved data refreshing from python api to command-line endpoint

docs/usage.rst, fv3config/fv3run/_docker.py, tests/test_fv3run.py
Fixes #48. Bind-mounts at the same level as specified by the config dict (directories if absolute path, filename if asset dict).
A side-effect of this is that calling run_docker will trigger an access request on the configuration dictionary. If the user does not have access, the command will fail (not really an issue, since it would also fail inside the docker container in that case). This did require mocking out the access in some other unit tests.
No documentation change needed as the lack of support for bind-mounting local files was undocumented. I did shift one documentation section at the suggestion of @oliverwm1 to make the order of information smoother.
Tests that the correct locations are bind-mounted are added.
=> added support for bind-mounting local files in run_docker

fv3config/fv3run/_kubernetes.py, fv3config/fv3run/_native.py, tests/test_fv3run.py
This PR ensures the `--oversubscribe` MPI flag is only used if the CPU count requires it. It adds the `--use-hwthread-cpus` flag so that hyperthreaded cores (such as on google VMs and MacBooks) will be used.
It also fixes a bug in `_create_job_object` by ensuring that the container name is alphanumeric.
=> Only use --oversubscribe flag if cpu count requires it

tests/test_fv3run.py
This fixes `test_fv3run_with_mocked_subprocess` to account for the case where the testing system is oversubscribed, and hence `--oversubscribe` is created as a flag to be passed to mpirun.
=> Fix test_fv3run for oversubscribed testing system

HISTORY.rst, RELEASE.rst
Added a RELEASE.rst file with release instructions. For us right now that means incrementing the version, tagging a commit, and pushing it to master. Further down the line this file can include instructions on deploying to pypi.
=> Instructions on incrementing and tagging a version

docs/usage.rst, fv3config/fv3run/__main__.py, fv3config/fv3run/_native.py, tests/test_fv3run.py
This allows a user to run the model with a python runfile already present in the
a docker image by setting the FV3_PYTHON_RUNFILE environmental variable. Because
the runfile is in many ways inseperable from the fortran code itself, it is
beneficial to bundle it with the other FV3 code.
Partially resolves #56
=> Optionally specify runfile with the environmental variable

fv3config/fv3run/_native.py, tests/test_fv3run.py
Instead of making the default flag to the python command in the mpi call be
python -m mpi4py -m fv3gfs.run
I accidentally made it call
python -m mpi4py -m fv3config.fv3run.
This has the effect of infinitely recursing into fv3config I think. I also used
the wrong main module name in the tests. I don't believe this effects any
workflows, since it hasn't been incorporated in the master fv3gfs-python image
yet. Both changes should be fixed now.
=> Fix bug where fv3config calls itself infinitely

docs/usage.rst, fv3config/_datastore.py, fv3config/filesystem.py, tests/test_asset_list.py
This adds the ability to add a custom field_table in the configuration dictionary to override the inferred version based on the microphysics scheme used.  The behavior is implemented as described in [this design document](https://paper.dropbox.com/doc/fv3config-supply-custom-field_table--At1mxQWSBpccxtSzp8aJXnOtAg-qnsdEpUuSPoimmslm1bPN) that @mcgibbon outlined earlier after a discussion with me and @oliverwm1.
I definitely see value in automatically setting the field_table used to prevent user-error as much as possible, so eventually I think we could look to somehow support the SHiELD use-case from that perspective; however, that introduces a few more complications that we'd have to think through:
- The microphysics scheme used is set with different namelist parameters than `imp_physics`. …
=> Add ability to use a custom field_table file

.gitignore, fv3config/fv3run/_kubernetes.py, tests/test_kubernetes.py
This small PR adds an option to provide an experiment label for the submitted Kubernetes job.  The label is used by `fv3net` to check for active jobs in the group while waiting for completion.
=> Feature/kube job label  (Necessary for workflow orchestration)

fv3config/_datastore.py
Enable setting an 'orographic_forcing' in the configuration yaml that can be a cloud bucket, while if this key missing or set to default will use the local data cache as it did before.
=> orographic_forcing can optionally be a cloud bucket

HISTORY.rst, fv3config/fv3run/_kubernetes.py, fv3config/fv3run/_native.py, tests/test_kubernetes.py
The PR changes the behavior of `run_kubernetes` to not ensure that the locations of the fv3config.yml and the output directory are remote. This assumption is too stringent. run_k8s should be able to use fv3configs stored in the container's file system and save to arbitrary locations (including ones in the container's filesystems or k8s local volume that is mounted).
Also fix a bug when generating the container name for docker images with an "_" in them. K8s does not allow "_" in the name of container.
=> Changes needed for the fv3net one-step jobs

fv3config/fv3run/_docker.py, fv3config/fv3run/_kubernetes.py, fv3config/fv3run/_native.py, tests/test_fv3run.py, tests/test_kubernetes.py
Changing the signature of run_native (e.g. to add an option changing the logging behavior), requires editing 3 other files: `run_kubernetes`, `run_docker`, and the `__main__.py`. This PR allows `run_kubernetes` and `run_docker` to pass arbitrary arguments to `run_native` provided that they are serializable with `json`. A side effect is that `run_kubernetes` can now take an actual configuration dictionary rather than a url pointing to one. 
It also tidies up the implementation of `run_kubernetes` especially. `run_docker` still has some unavoidable logic to do with creating the bind-mounts, but is slightly cleaner now too.
=> Pass arbitrary kwargs from run_docker/run_k8s to run_native

docs/usage.rst, fv3config/__init__.py, fv3config/_asset_list.py, fv3config/_datastore.py, fv3config/caching.py, fv3config/filesystem.py, tests/test_cache.py, tests/test_datastore.py, tests/test_forcingdata.py
Major changes:
- Adds a routine `fv3config.do_remote_caching` which sets the default caching behavior for remote files.
Minor changes:
- Renamed the `cache_location` module to `caching`.
=> Allow enabling and disabling caching

HISTORY.rst, docs/usage.rst, fv3config/_asset_list.py, fv3config/filesystem.py, fv3config/fv3run/__main__.py, fv3config/fv3run/_docker.py, fv3config/fv3run/_kubernetes.py, fv3config/fv3run/_native.py, fv3config/fv3run/_native_main.py, tests/test_fv3run.py
Major changes:
- Added `--kubernetes` command-line flag to output a kubernetes config yaml to stdout
- When output location is set to a local path, the job now runs in that output location instead of in a temporary directory which then gets copied. This is done both to reduce copying time for large jobs, and to improve visibility of model behavior while running.
Minor changes:
- Updated `filesystem.is_local_path` naming to be package-private instead of module-private
- Fixed an issue where the subprocess-wrapped run_native lived inside an imported module, resulting in python warnings
=> Add --kubernetes flag and run model in outdir when outdir is local

HISTORY.rst, fv3config/fv3run/__main__.py, fv3config/fv3run/_docker.py, fv3config/fv3run/_kubernetes.py, fv3config/fv3run/_native.py, tests/test_fv3run.py
All of our runtime environments (the linux shell, docker, and kubernetes) have powerful tools for manipulating the stdout and stderr streams, but fv3run captures these streams and instead puts them in relatively inaccessible files. This makes real time debugging and monitoring of k8s jobs especially challenging. In general, it is more flexible to pipe the outputs to stderr and stdout and let the user leverage the power of linux shell, pipes, and commands like `tee` to put the outputs where they want. 
As an example
fv3run fv3config.yml output 2> output/stderr.log > output/stdout.log
will emulate the previous behavior provided the output directory is made
first.
Changes
* Avoid redirecting stderr and stdout when using the `fv3run` CLI unless the `--capture-output` argument is passed to …
=> Make output capturing an optional behavior

tests/test_kubernetes.py
This PR adds an ignore flag to the warning that the kubernetes output directory is a local path and that output data will not be available, since the use of a local path is by design in this test (and we're not trying to get output data). This PR returns the fv3config tests to a state where no warnings should be printed when they run.
I'd consider this change too small to document in the HISTORY.rst.
=> Ignore expected warning during kubernetes get_job test

HISTORY.rst, fv3config/__init__.py, setup.cfg, setup.py
Update version to v0.4.0 with removal of old-style data, so we can reference it from fv3gfs-python.
=> Release v0.4.0

HISTORY.rst, examples/create_rundir.py, examples/create_rundir.sh, examples/create_rundir_from_remote.py
@SpiderMonkey1975 needs to create a run directory so he can run the model manually using mpirun instead of via `fv3run`. This updates the example script so it can be used plug-and-play for that purpose.
=> updated create_rundir example to accept external arguments

HISTORY.rst, docs/usage.rst, fv3config/cli.py, setup.py
This commits installs a write_run_directory CLI into the user path
which can be used to write local rundirectories from local or remote
yaml files.
Resolves #3
=> Add a write_run_directory CLI

fv3config/__init__.py
This PR makes asset_list_from_path a public API function. This function does exactly what is needed to get the multiple files that compose a keras model added to the asset list for copying over to the run directory, but it is not currently public.
=> Make asset_list_from_path public

requirements_dev.txt
The Jenkins tests broke due to a new gcsfs version coming out which is incompatible with the older pinned fsspec version. Updating the requirements for both packages to their latest versions and pinning them has fixed the issue.
=> Fix tests on Jenkins due to dependency breakage

.jenkins/actions/test.sh, fv3config/_asset_list.py, tests/test_asset_list.py, tests/test_write_run_directory.py
Many uses of the python wrapper require a configuration dictionary to be
saved as a yaml file named `fv3config.yml` in the run directory root.
This PR adds this simple capability.
The test is a little tautological, but oh well...
=> Copy configuration dict into rundirectory

.jenkins/jenkins.sh
Remove a check which makes sure the the hostname is contained in host.
Reason: hostname is set by GCP to be `ubuntu18.04-...`.
=> Remove host/shorthost check

HISTORY.rst, fv3config/__init__.py, fv3config/filesystem.py, tests/c12_config.yml, tests/conftest.py, tests/test_forcingdata.py, tests/test_fv3run.py
This PR modifies the test suite to run fully offline. It makes two changes:
- while the tests are running, get_fs is modified so it returns a MemoryFileSystem which accepts paths with a gs protocol
- run_docker tests which actually run the model are removed. This feature is deprecated, and also sufficiently tested by unit tests on run command generation
This was done for a few reasons:
- it is generally good practice to have your tests not depend on network connectivity, to avoid intermittent failures
- we are making our google cloud buckets private, and can no longer depend on the data which was being accessed
- we would like to avoid egress fees when running tests on Piz Daint
=> Remove network dependency of test suite

fv3config/_datastore.py, fv3config/config/derive.py, tests/test_nudging.py, tests/test_tables.py
Check for the existence of `coupler.res` amongst all assets of given configuration dictionary. This fixes a bug introduced in #104 which required `initial_conditions` to be a path, whereas it can also be an asset or list of assets.
As part of this:
1. move `get_resolution` from `derive.py` to `_datastore.py` (this is the only module in which this function is used)
1. add two tests of `get_current_date` which exercise the two code paths of that function which are not currently tested
=> Check for coupler.res among all assets

fv3config/filesystem.py
This PR fixes the `gcsfs` filesystem initialization after flipping the "requester pays" switch on the `gs://vcm-fv3config` bucket.  The adjustment includes default project ID for the active service account to be used for billing.
From the GCSFS API page:
```
requester_pays : bool, or str default False
Whether to use requester-pays requests. This will include your project ID project
in requests as the userPorject, and you’ll be billed for accessing data from requester-pays
buckets. Optionally, pass a project-id here as a string to use that as the userProject.
```
Based on local tests, `requester_pays=True` should be fine for all of our buckets:
```
In [1]: import fsspec
In [2]: fsspec.filesystem("gs").exists("gs://vcm-fv3config")
Out[2]: False
In [3]: fsspec.filesystem("gs", …
```
=> Add requester pays to GCSFilesystem initialization

fv3config/config/derive.py, tests/test_tables.py
Fixes bug (and adds test) for getting coupler res filename when using a directory for initial conditions. Bug happened because if statement checked if `target_location` was equal to `INPUT` but `asset_list_from_path` returned `INPUT/`. Fixes bug by using joined path in `_get_coupler_res_filename`.
=> Fix getting coupler_res filename when using directory for initial conditions

.jenkins/actions/test.sh
While not failling, tests are cluttered with error messages along the lines `error: invalid command 'bdist_wheel'`. This fixes this by pre-pip-installing wheel.
=> Explicitly install wheel before requirements to remove wheel error messages

fv3config/config/derive.py
Use the fv3config `get_fs` to instantiate the fileststem used to grab the coupler.res file when getting the date date instead of `fsspec.open`.  This ensures that anything in the public `fv3config` bucket will have the `requester_pays=True` in the `GCSFSFilesystem` creation.
=> Fix date retrieval from coupler_res to use get_fs instead of fsspec.open

requirements_dev.txt
backoff is a package requirement already listed in setup.py. This PR adds it to requirements_dev.txt. This is required to get readthedocs to build again.
=> Add backoff to requirements_dev.txt

fv3config/filesystem.py, requirements.txt, requirements_dev.txt
I've been getting corrupted file errors occasionally. Needed to bump gcs version to 0.7.0 to get the `gcsfs.utils.ChecksumError`.
Resolves #117
=> Validate md5 checksum of gcs downloads

HISTORY.rst, fv3config/_asset_list.py, fv3config/config/nudging.py, fv3config/config/rundir.py
This will aid in debugging if the `write_run_directory` command fails. It is also useful for monitoring, especially when many assets are being copied and `write_run_directory` takes minutes to complete.
Resolves #115 
Edit: also fixes an unrelated warning about importing from collections instead of collections.abc
=> Add logging to writing of run directory

HISTORY.rst, docs/usage.rst, fv3config/__init__.py, fv3config/_asset_list.py, fv3config/config/__init__.py, fv3config/config/diag_table.py, fv3config/config/namelist.py, requirements.txt, requirements_dev.txt, tests/test_asset_list.py, tests/test_diag_table.py, tests/test_namelist.py
It is useful to have a richer representation of the `diag_table` item in fv3config configuration dictionaries.
This PR adds a `DiagTable` class and associated `DiagFileConfig` and `DiagFieldConfig` dataclasses. The `DiagTable` class has `__repr__` and `from_str` methods which allow going between the Fortran-expected string representation of the `diag_table` and the python representation. It also includes `asdict` and `from_dict` methods, which are useful for serializing/deserializing the `diag_table` item to/from YAML.
[dacite](https://github.com/konradhalas/dacite) is added as a requirement, as it provides useful functionality for going from a dict to a DataClass with type checking.
This PR does not introduce any breaking changes. If a user provides a path for the `diag_table`, that file …
=> DiagTable class

HISTORY.rst, fv3config/config/nudging.py, fv3config/config/rundir.py, tests/conftest.py, tests/test_write_run_directory.py
fv3config should provision the necessary `patch_files` at the time of `write_run_directory` if nudging is activated. This will simplify scripts that use `fv3config` since they won't have to do this themselves.
=> Update for nudging on write_run_directory if necessary

fv3config/_asset_list.py, fv3config/fv3run/_native.py, tests/test_asset_list.py, tests/test_write_run_directory.py
A use of `yaml.safe_dump` within the `get_fv3config_yaml_asset` function prevented the writing of run directories when a config object contained a `DiagTable` class for the `diag_table` entry. This PR replaces that usage with `fv3config.dump` and adds a relevant test.
=> Replacing remains yaml usages with fv3config load/dump

HISTORY.rst, docs/usage.rst, fv3config/__init__.py, fv3config/_asset_list.py, fv3config/cli.py, fv3config/config/__init__.py, fv3config/config/nudging.py, fv3config/config/rundir.py, setup.py, tests/test_nudging.py, tests/test_write_run_directory.py
Currently the `write_run_directory` function mutates the input if nudging is enabled. It also does so (in a subtle way) if the `config["initial_conditions"]` entry is a list. This PR adds tests for these cases and fixes them.
Resolves #130
=> Ensure write_run_directory does not mutate input config

HISTORY.rst, fv3config/filesystem.py, requirements.txt, requirements_dev.txt, tests/test_fv3run.py
The retry logic should be unnecessary with the next version of gcsfs.
Closes #140
=> Remove gcsfs retry logic

README.rst, fv3config/filesystem.py, tests/test_filesystem.py
get_fs does not support file systems other than gcsfs or file. It also
has special handling of requester_pays that breaks some typical
authentication patterns, where the key file is pointed to by
GOOGLE_APPLICATION_CREDENTIALS, but no default google project is set.
* Remove the special handling and generalize `get_fs` to work with any ffsspec filesystem
fsspec now offers a way to configure these flags via environment
variables. In this case requester pays can be turned on like this:
export FSSPEC_GS_REQUESTER_PAYS=True
Resolves #143.
=> Generalize fsspec instantiation

setup.py
PyPI requires classifiers come from [this list](https://pypi.org/classifiers/).  This appears to be the appropriate one for Apache-licensed tools.
=> Fix license classifier in `setup.py`

HISTORY.rst, fv3config/__init__.py, fv3config/_asset_list.py, fv3config/_asset_list_config.py, fv3config/_datastore.py, fv3config/_tables.py, fv3config/config/derive.py, fv3config/config/initial_conditions.py, fv3config/config/namelist.py, fv3config/config/rundir.py, fv3config/filesystem.py, tests/test_asset_list.py, tests/test_forcingdata.py, tests/test_namelist.py, tests/test_tables.py
I would like to enable wandb (and other metadata tracking) integrations for assets supported by fv3config. The "asset list" is the natural target for this, but is not currently a complete representation of the config dict since there is lingering logic in the `write_run_directory` function.
* push all config-handling logic into `config_to_asset_list`
* make `config_to_asset_list` public API
This will allow usages like this downstream:
```
assets = fv3config.config_to_asset_list(config)
for asset in assets:
if asset["source_location"].startswith("wandb://"):
artifact = run.use_artifact(...asset)
path = artifact.download()
asset["source_location"] = path
fv3config.write_asset(asset, "rundir")
```
To reviewers: I recommend reviewing commit-by-commit. I tried to isolate the refactors into …
=> Make fv3config.config_to_asset_list public API

README.rst
The `FSSPEC_GS_REQUESTER_PAYS` environment variable is always treated as a string, which is interpreted as the project id rather than a boolean flag (see [here](https://github.com/fsspec/gcsfs/blob/e4c16db7f59e0f243965f015e95996f9e7fe9665/gcsfs/core.py#L339-L344)).  Therefore when setting the `requester_pays` option via the environment variable, one must always use the project id.
```
$ export FSSPEC_GS_REQUESTER_PAYS=True
$ python
>>> import fsspec
>>> url = "gs://vcm-fv3config/config/yaml/default/v0.3/fv3config.yml"
>>> fs, *_ = fsspec.get_fs_token_paths(url)
>>> fs.requester_pays
'True'
>>> len(fs.cat(url))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/spencerc/miniconda3/envs/fv3net-testing/lib/python3.8/site-packages/fsspec/asyn.py", line 85, in …
```
=> Update instructions for requester pays
